on:
  push:
    branches-ignore:
    - master

name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # uses: mr-smithers-excellent/docker-build-push@v6
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # image: repo/image
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: juliocsg/test-gactions:${{ github.sha }}
